import { expect } from '@playwright/test';
import { Given, When, Then } from '../../support/fixtures';

// Generated by AI (ai:generate --implement-missing) — review
Then('the prices end up sorted from highest to lowest', async ({ inventoryPage }) => {
  const prices = await inventoryPage.itemPricesList();
  const sorted = [...prices].sort((a, b) => b - a);
  expect(prices).toEqual(sorted);
});

// Generated by AI (ai:generate --implement-missing) — review
Then('the first product is the most expensive', async ({ inventoryPage }) => { await inventoryPage.firstItemIsMostExpensive(); });
