# Generated by AI (ai:generate) — review before merging
@saucedemo @ai-generated
Feature: SauceDemo product sorting
  As an authenticated SauceDemo user
  I want to sort products by price
  So that I can verify the ordering of the product list

  Background:
    Given the user is on the SauceDemo login page
    And logs in with user "standard_user" and password "secret_sauce"

  Scenario: Sort products from highest to lowest price
    When sorts the products by "Price (high to low)"
    Then the prices end up sorted from highest to lowest
    Then the first product is the most expensive
