import 'dotenv/config';
import Anthropic from '@anthropic-ai/sdk';
import { appendFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateScenarioCore } from './generateScenarioCore';
import { implementMissingSteps } from './implementMissingSteps';
import { SUITES, type Suite } from './types';

interface CliArgs {
  description: string;
  suite: Suite;
  name?: string;
  implementMissing: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const positional: string[] = [];
  let suite: string | undefined;
  let name: string | undefined;
  let implementMissing = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--suite') {
      suite = argv[++i];
    } else if (arg === '--name') {
      name = argv[++i];
    } else if (arg === '--implement-missing') {
      implementMissing = true;
    } else {
      positional.push(arg);
    }
  }

  const description = positional.join(' ').trim();
  if (!description) {
    throw new Error('Missing scenario description. Usage: npm run ai:generate -- "description" --suite demoqa|saucedemo');
  }
  if (!suite || !SUITES.includes(suite as Suite)) {
    throw new Error(`--suite is required and must be one of: ${SUITES.join(', ')}`);
  }

  return { description, suite: suite as Suite, name, implementMissing };
}

function slugify(text: string): string {
  return text
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60);
}

async function main() {
  const repoRoot = process.cwd();
  const args = parseArgs(process.argv.slice(2));

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('Missing ANTHROPIC_API_KEY (set it in .env, see .env.example)');
  }
  const anthropic = new Anthropic({ apiKey });
  const model = process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-5';

  const { featureText, missingLines } = await generateScenarioCore({
    description: args.description,
    suite: args.suite,
    anthropic,
    model,
    repoRoot,
  });

  const header = '# Generated by AI (ai:generate) — review before merging';

  const outDir = join(repoRoot, 'features', args.suite);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const slug = args.name ? slugify(args.name) : slugify(args.description);
  const outPath = join(outDir, `${slug}.feature`);

  // Written early: --implement-missing needs a real file under features/<suite>/ to be able
  // to run it with bddgen + playwright test.
  writeFileSync(outPath, `${header}\n${featureText}\n`, 'utf-8');

  let allMissing = missingLines;
  if (args.implementMissing && missingLines.length > 0) {
    const report = await implementMissingSteps(anthropic, model, args.suite, missingLines, outPath, repoRoot);
    allMissing = report.unresolved;
  }
  const missingBlock =
    allMissing.length > 0
      ? `\n# Missing steps (not implemented, review/implement before enabling this scenario):\n${allMissing.map((s) => `#   ${s}`).join('\n')}\n`
      : '';

  if (missingBlock) appendFileSync(outPath, missingBlock, 'utf-8');

  console.log(`\nScenario generated: ${outPath}`);
  if (allMissing.length > 0) {
    console.log('\nMissing steps:');
    for (const step of allMissing) console.log(`  - ${step}`);
  } else {
    console.log('All steps used already existed or were implemented and verified.');
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
